apiVersion: v1
kind: Namespace
metadata:
  name: bamboo
---
apiVersion: v1
kind: LimitRange
metadata:
  name: bamboo
  namespace: bamboo
spec:
  limits:
  - type: Pod
    max:
      cpu: 100
      memory: 200Gi
    min:
      cpu: 0
      memory: 0
  - type: Container
    max:
      cpu: 100
      memory: 200Gi
    min:
      cpu: 0
      memory: 0
    default:
      cpu: 0
      memory: 0

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: bamboo
  namespace: bamboo
spec:
  hard:
    cpu: 2400
    memory: 4800Gi
    persistentvolumeclaims: 0
    pods: 1000
    replicationcontrollers: 1000
    resourcequotas: 1
    secrets: 1
    services: 0
---
