apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v1.0.2
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.0.2
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v1.0.2
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.0.2
    spec:
      nodeSelector:
        master: "true"
      volumes:
        - name: config
          hostPath:
            path: /var/lib/kubelet/kubeconfig
      containers:
        - image: 61.160.36.122:8080/sigmas/heapster:v1.0.2
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 2
              memory: 4Gi
          command:
            - /heapster
            - --source=kubernetes:https://192.168.0.1?inClusterConfig=false&insecure=true&auth=/var/lib/kubelet/kubeconfig&useServiceAccount=false
            - --metric_resolution=60s
            - --logtostderr=true
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /var/lib/kubelet/kubeconfig
