apiVersion: v1
kind: ReplicationController
metadata:
  name: kubedash-v10
  namespace: kube-system
  labels:
    k8s-app: kubedash
    version: v10
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kubedash
    version: v10
  template:
    metadata:
      labels:
        k8s-app: kubedash
        version: v10
        kubernetes.io/cluster-service: "true"
    spec:
      hostNetwork: true
      nodeSelector:
        master: "true"
      containers:
      - image: sigmas/kubedash:v0.2.2
        name: kubedash
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
        command:
        - /kubedash
        - -port=7011
        - -logtostderr=true
        ports:
        - name: kubedash-port
          hostPort: 7011
          containerPort: 7011

---

kind: Service
apiVersion: v1
metadata:
  name: kubedash
  namespace: kube-system
  labels:
    k8s-app: kubedash
    version: v10
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kubedash"
spec:
  ports:
  - port: 7011
    targetPort: kubedash-port
  selector:
    k8s-app: kubedash
